install-dist:  ## Install backend dependencies
	rm -rf  ~/.composer composer.lock vendor && composer install --prefer-dist -vvv

install-source:  ## Install backend dependencies
	rm -rf  ~/.composer composer.lock vendor && composer install --prefer-source -vvv